version: "3.8"

services:
  slim_api:
    build: ./slim_api
    container_name: slim_api
    entrypoint: [ "sh", "./.docker/entrypoint.sh" ]
    ports:
      - '9000:9000'
    volumes:
      - ./slim_api:/var/www/slim_api

  slim_nginx:
    build: .docker/nginx
    container_name: slim_nginx
    tty: true
    ports:
      - '8080:8080'
    volumes:
      - ./slim_api:/var/www/slim_api
      - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - slim_api