version: "3.8"

services:
  slim_api:
    build: ./slim_api
    container_name: slim_api
    entrypoint: [ "sh", "./.docker/entrypoint.sh" ]
    ports:
      - '9000:9000'
    volumes:
      - ./slim_api:/var/www/html/slim_api

  slim_nginx:
    build: .docker/nginx
    container_name: slim_nginx
    tty: true
    ports:
      - '8080:8080'
    volumes:
      - ./slim_api:/var/www/html/slim_api
    depends_on:
      - slim_api

  slim-db:
    image: postgres:15-alpine
    container_name: slim-db
    restart: always
    environment:
      POSTGRES_DB: cccat17
      POSTGRES_USER: cccat17
      POSTGRES_PASSWORD: slim_cccat17
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: